spring.application.name=TransporteApplication
server.port=8080
# H2
spring.datasource.url=jdbc:h2:mem:transporte
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# H2 Console deshabilitada
spring.h2.console.enabled=false