version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: contenedor-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mi_base_datos
      MYSQL_USER: mi_usuario
      MYSQL_PASSWORD: user_password_secreta
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: administrador-web
    restart: always
    links:
      - mysql-db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306

volumes:
  mysql_data:
